# This is the name of the workflow, which will be displayed in the "Actions" tab of your GitHub repository.
name: Deploy to Netlify

# This section defines the trigger for the workflow.
# In this case, the workflow runs on any 'push' event to the 'master' or 'main' branch.
on:
  push:
    branches:
      - master
      - main # It's good practice to include 'main' as the modern default.

jobs:
  build-and-deploy:
    # The type of virtual machine to run the job on. 'ubuntu-latest' is a cost-effective and common choice.
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checks out your repository's code onto the virtual machine.
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Sets up the specified version of Node.js.
      # It's important to use a version compatible with your project and Netlify's environment.
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Using a recent Long-Term Support (LTS) version.

      # Step 3: Installs project dependencies. 'npm ci' is used instead of 'npm install'
      # because it's faster and ensures a clean, consistent installation based on package-lock.json.
      - name: Install dependencies
        run: npm ci

      # Step 4: Runs the test suite. If any test fails, the workflow will stop here,
      # preventing a broken deployment.
      - name: Run tests
        run: npm test

      # Step 5: Builds the application for production. This command creates the 'dist' folder.
      - name: Build application
        run: npm run build

      # Step 6: Deploys the built site to Netlify using a dedicated action.
      - name="Deploy to Netlify"
        uses: nwtgck/actions-netlify@v3
        with:
          publish-dir: './dist' # The folder that contains the built site.
          production-branch: main # Specify your production branch.
          github-token: ${{ secrets.GITHUB_TOKEN }} # Token for the action to post comments on commits.
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }} # Your Netlify personal access token.
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}       # The API ID of your Netlify site.